---
title: "Tidyverse"
author: "Adrian Florea"
---

# Prepare Data for Analysis

```{r}
#| eval: true
#| message: false

# Loading Libraries
library(tidyverse)
library(readxl)

# Importing Files
bikes_tbl <- read_excel("~/GitHub/ss24-bdsb-Adrian-0402/content/01_journal/01_tidyverse_files/01_bike_sales/01_raw_data/bikes.xlsx")
orderlines_tbl <- read_excel("~/GitHub/ss24-bdsb-Adrian-0402/content/01_journal/01_tidyverse_files/01_bike_sales/01_raw_data/orderlines.xlsx")
bikeshops_tbl <- read_excel("~/GitHub/ss24-bdsb-Adrian-0402/content/01_journal/01_tidyverse_files/01_bike_sales/01_raw_data/bikeshops.xlsx")

# Joining Data 
bike_orderlines_joined_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))

# Wrangling Data
bike_orderlines_wrangled_tbl <- bike_orderlines_joined_tbl %>%
  separate( col = location,
            into = c("city","state"),
            sep = ", ") %>% 
  mutate(total.price = price * quantity) %>% 
  select(-...1, -gender) %>%
  rename(bikeshop = name) %>% 
  set_names(names(.) %>% str_replace_all("\\.", "_"))

```

# Analysis of the Data

## By Location (State)

```{r plot1, fig.width=15, fig.height=10}
#| eval: true
#| message: false
#| fig-cap: "Revenue by different states"
# Manipulate
sales_by_state_tbl <- bike_orderlines_wrangled_tbl %>% 
  select(state, total_price) %>% 
  group_by(state) %>% 
  summarize(sales = sum(total_price)) %>% 
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

#Visualize
sales_by_state_tbl %>%
  ggplot(aes(x = state, y = sales)) +
  geom_col(fill = "#16C17C") +
  geom_label(aes(label = sales_text)) +
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(
    title    = "Revenue by state",
    x = "", # Override defaults for x and y
    y = "Revenue"
  )
```

## By Location (State) **and** year

```{r plot2, fig.width=15, fig.height=10}
#| eval: true
#| message: false
#| fig-cap: "Revenue by different states and year"
# Manipulate
library(lubridate)

sales_by_state_year_tbl <- bike_orderlines_wrangled_tbl %>%
  select(state, order_date, total_price) %>% 
  mutate(year = year(order_date)) %>% 
  group_by(year, state) %>% 
  summarize(sales = sum(total_price)) %>% 
  ungroup() %>% 
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

# Visualize
sales_by_state_year_tbl %>%
  
  # Set up x, y, fill
  ggplot(aes(x = year, y = sales, fill = state)) +
  
  # Geometries
  geom_col() + # Run up to here to get a stacked bar plot
  
  # Facet
  facet_wrap(~ state) +
  
  # Formatting
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".",
                                                    scale = 0.000001,
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = "m €")) +
  labs(
    title = "Revenue by year and state",
    fill = "States" # Changes the legend name
  )
```
